version: "3.6"
services:
  claratrain:
    container_name: claradevday-pt #claradevday-ohif
    image: nvcr.io/nvidian/dlmed/clara-train-sdk:v4.0.ea2-2008-rc3
    hostname: claratrain
    ports:
      - "5000:5000" #mapped as http://<machinename>:ohifport/aiaa/
      - "8899:8888" #mapped as http://<machinename>:ohifport/notebooks/
    volumes:
      - ../../../:/claraDevDay/
    command: "jupyter lab /claraDevDay --ip 0.0.0.0 --allow-root --no-browser"
#    command: "jupyter lab /claraDevDay --ip 0.0.0.0 --allow-root --no-browser --config /claraDevDay/AIAA/OHIF/orthanc/config/jupyter_notebook_config.py"
#    command: "/bin/bash"
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
#############################################################
  ohif:
    container_name: aiaa-ohif-orthanc
    build:
      # Project root
      context: ./docker/
      # Relative to context
      dockerfile: ./Dockerfile
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
    - orthanc
    ports:
      - "3030:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/ohif_orthanc_default.js:/usr/share/nginx/html/app-config.js:ro
#############################################################
  orthanc:
    image: jodogne/orthanc-plugins
    container_name: aiaa-orthanc
    hostname: orthanc
    ports:
#      - "3042:8042"  # already covered by nginx #mapped as http://<machinename>:ohifport/pacs/
      - "3043:4242"
    volumes:
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data 
      - /raid/users/aharouni/dockers/orthanc/orthanc-db/:/var/lib/orthanc/db/
      #- ${ConfigLocalPath}/orthanc-db/:/var/lib/orthanc/db/
    command: "/etc/orthanc --verbose"
